name: DeployCF

on:
  push:
    branches: [ "deploy_cloudflare" ]
  pull_request:
    branches: [ "deploy_cloudflare" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          email: ${{ secrets.CF_EMAIL }}
        env:
          USER: root
